apiVersion: v1
kind: Service 
metadata:
  name: dev-deployment-service
  namespace: dev 
spec:
  type: LoadBalancer 
  selector: 
    app: dev-app 
  ports:
    - name: http-port 
      port: 8080
      targetPort: 8080