apiVersion: v1
kind: Service 
metadata:
  name: prod-deployment-service
  namespace: prod
spec:
  type: LoadBalancer 
  selector: 
    app: production-app 
  ports:
    - name: http-port 
      port: 8080
      targetPort: 8080